### ISSUE TITLE
uncomitted changes?

### ISSUE THREAD

**Issue by adoig-umass** [jsalignon/cactus#26]
Hello, looking forward to using this pipeline. Seems very useful. Trying to run the test dataset and when trying to collect references I ran into a couple issues.

The nextflow.config file contained a params.enable_conda = false which nextflow did not seem to recognize, I changed that to conda.enabled = false. This resolved that error message.

When trying to download with command 
`nextflow run jsalignon/cactus/scripts/download/download.nf --references --species worm -r main -latest`

the following error is thrown... 
jsalignon/cactus contains uncommitted changes -- cannot pull from repository

I am new to github and bioinformatics but I think this means its a github issue?

**Comment by maxulysse** [comment]
Hi @adoig-umass.
I'd recommend either to specify your own custom config file.
Or if you want to edit the pipeline, clone it and run it locally.

Nextflow is trying to read the file in the hidden nextflow folder which you probably modified. Which is why you're getting this message.

**Comment by adoig-umass** [comment]
Okay, thank you. I think there are some good suggestions here for me to try after some reading about config files/cloning.
